# Generated by Django 5.1.7 on 2025-05-01 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0002_workerrole_vehicle_type_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Washing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client_name', models.CharField(max_length=100)),
                ('client_phone', models.CharField(max_length=20)),
                ('vehicle_plate', models.CharField(max_length=20)),
                ('washing_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pagado', 'Pagado'), ('no_pagado', 'No Pagado'), ('arm', 'ARM')], max_length=10)),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='parking.vehicle_type')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('parking_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parking.parking')),
                ('washing', models.ManyToManyField(to='settlement.washing')),
            ],
        ),
    ]
