# Generated by Django 5.1.7 on 2025-05-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto final'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=35.0, max_digits=5, verbose_name='Porcentaje de descuento (%)'),
        ),
    ]
