# Generated by Django 5.1.7 on 2025-05-31 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0003_settlement_created_at_settlement_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=35.0, max_digits=5, verbose_name='Trabajadores (%)'),
        ),
    ]
