# Generated by Django 5.1.7 on 2025-05-31 00:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0004_alter_settlement_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='washing',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
