# Generated by Django 5.1.7 on 2025-05-31 00:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0005_alter_settlement_date_alter_washing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, unique=True),
        ),
        migrations.AlterField(
            model_name='washing',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='washing',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
