# Generated by Django 5.1.7 on 2025-06-01 00:59

import settlement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0006_alter_settlement_date_alter_washing_client_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=settlement.models.get_upload_path),
        ),
    ]
