# Generated by Django 5.1.7 on 2025-06-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0008_alter_settlement_washing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='washing',
            field=models.ManyToManyField(blank=True, to='settlement.washing'),
        ),
    ]
