# Generated by Django 5.1.7 on 2025-06-02 00:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0009_alter_settlement_washing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
