# Generated by Django 5.1.7 on 2025-06-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0010_alter_settlement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='parking_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total'),
        ),
    ]
