# Generated by Django 5.1.7 on 2025-06-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0011_settlement_parking_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washing',
            name='status',
            field=models.CharField(choices=[('pagado', 'Pagado'), ('no_pagado', 'No Pagado'), ('arm', 'ARM'), ('cancelado', 'Cancelado')], max_length=10),
        ),
    ]
