# Generated by Django 5.1.7 on 2025-06-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0012_alter_washing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settlement',
            name='image',
        ),
    ]
