# Generated by Django 5.1.7 on 2025-07-18 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0013_remove_settlement_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settlement',
            options={'ordering': ['-created_at']},
        ),
    ]
