# Generated by Django 5.1.7 on 2025-07-18 17:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0014_alter_settlement_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
