# Generated by Django 5.1.7 on 2025-04-03 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('vehicle', models.CharField(choices=[('MOTO', 'Moto'), ('AUTOMOVIL', 'Automóvil'), ('TURBO', 'Turbo'), ('CAMIONETA', 'Camioneta'), ('CARRITO', 'Carrito')], max_length=50)),
                ('license_plate', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('document_type', models.CharField(blank=True, choices=[('CEDULA', 'Cédula'), ('NIT', 'NIT')], max_length=10, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parking_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parking.parking')),
            ],
        ),
        migrations.CreateModel(
            name='MoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('PARKING_OCCASIONAL', 'Parqueo Ocasional'), ('MONTHLY_PAYMENT', 'Mensualidad'), ('WASH', 'Lavado')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
            ],
        ),
    ]
