# Generated by Django 5.1.7 on 2025-05-19 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
        ('parking', '0002_workerrole_vehicle_type_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='invoice',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='parking.vehicle_type'),
        ),
    ]
